### ISSUE TITLE
Maybe a better way to get access to mysql cli?

### ISSUE THREAD

**Issue by movsb** [JSurf/docker-rpi-mariadb#5]
Hi, I'm currently using docker-compose, and below is the `docker-compose.yml`:

```yaml
---
version: "2"
services:
  mysql:
    image: jsurf/rpi-mariadb
    container_name: mysql
    user: "1000"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - ./mysql/config:/etc/mysql
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
```

And, the command to connect to MySQL is:

```bash
#!/bin/bash

exec docker exec -it mysql mysql -h mysql -u root -p
```

More light-weighted?

Thanks.
